# Generated by Django 5.2.15 on 2026-06-12 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_user_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expertise_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organizational_entity', models.CharField(blank=True, db_index=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('research_summary', models.TextField(blank=True, max_length=1200)),
                ('is_public', models.BooleanField(default=True, help_text='Controls whether this profile appears in public directory views.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name', 'user__email'),
            },
        ),
        migrations.CreateModel(
            name='ProfileExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.profile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.expertiseterm')),
            ],
            options={
                'ordering': ('term__name',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise_terms',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='directory.ProfileExpertise', to='directory.expertiseterm'),
        ),
        migrations.AddConstraint(
            model_name='profileexpertise',
            constraint=models.UniqueConstraint(fields=('profile', 'term'), name='unique_profile_expertise'),
        ),
    ]
